language: node_js
git:
  depth: 1
node_js:
  - stable
env:
  global:
    - secure: 
    - GITHUB_REPO: "camilin87/supplement-facts"
    - BRANCH_TO_MERGE_INTO: "gh-pages"
after_success:
  - bash deploy.sh
